import React, { useState, useEffect } from 'react';
import { Card } from '@/components/ui/card';
import { cn } from '@/lib/utils';
import { Check, X, ChevronDown, ChevronUp, Sparkles } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { ModelIcon, ModelName } from './ModelIcon';
import { Badge } from '@/components/ui/badge';

interface AmbossAnswerProps {
  optionLetter: 'A' | 'B' | 'C' | 'D' | 'E';
  optionText: string;
  isCorrect: boolean;
  isRevealed: boolean;
  percentage: number | null; // For stats, e.g. 97, or null if no data
  onClick: () => void;
  explanation?: string;
  children?: React.ReactNode;
  wasAttempted?: boolean; // Whether this answer was tried but not yet revealed
  isSelected?: boolean; // Whether this specific answer was clicked by the user
  showPercentage?: boolean; // Whether to show percentage (premium feature)
  modelIcons?: ModelName[]; // Array of model names that chose this answer
  showUpgradePrompt?: boolean; // Whether to show upgrade prompt (free user reached limit)
  isAIGenerated?: boolean; // Whether this option was completely generated by AI (original was empty)
}

export const AmbossAnswer: React.FC<AmbossAnswerProps> = ({
  optionLetter,
  optionText,
  isCorrect,
  isRevealed,
  percentage,
  onClick,
  explanation,
  children,
  wasAttempted = false,
  isSelected = false,
  showPercentage = true,
  modelIcons = [],
  showUpgradePrompt = false,
  isAIGenerated = false,
}) => {
  const [isExpanded, setIsExpanded] = useState(false);
  const [wasRevealed, setWasRevealed] = useState(false);
  const navigate = useNavigate();

  // Reset when moving to a new question
  useEffect(() => {
    if (!isRevealed && wasRevealed) {
      // Moving to a new question - reset everything
      setIsExpanded(false);
      setWasRevealed(false);
    }
    if (isRevealed && !wasRevealed) {
      setWasRevealed(true);
    }
  }, [isRevealed, wasRevealed]);

  const handleClick = () => {
    const hasCommentsContent = Boolean(explanation || children);
    const canExpand = hasCommentsContent || showUpgradePrompt;
    // Before reveal, always allow expanding to show AI comments (or fallback),
    // and also trigger the answer selection.
    if (!isRevealed) {
      if (canExpand) {
        setIsExpanded((prev) => !prev);
      }
      onClick();
      return;
    }

    // After reveal, only toggle expansion if there is content to show.
    if (canExpand) {
      setIsExpanded((prev) => !prev);
    }
    // When revealed and no comments, do nothing.
  };
  const stateClasses = isRevealed
    ? isCorrect
      ? 'border-y-[#0b8363] bg-[#d0f1e8] z-10 dark:border-emerald-500 dark:bg-emerald-900/40'
      : wasAttempted
        ? 'border-y-red-200 bg-red-50 dark:border-red-500 dark:bg-red-900/40' // Keep highlight but darken in dark mode
        : 'border-y-slate-200 dark:border-slate-700'
    : wasAttempted
      ? 'border-y-red-200 bg-red-50 hover:bg-red-100 dark:border-red-500 dark:bg-red-900/40 dark:hover:bg-red-900/60'
      : 'border-y-slate-200 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800';

  const letterClasses = isRevealed
    ? isCorrect
      ? 'text-emerald-800 dark:text-emerald-300'
      : 'text-red-700 dark:text-red-300'
    : wasAttempted
      ? 'text-red-700 dark:text-red-300'
      : 'text-slate-600 dark:text-slate-200';

  const icon = isRevealed ? (
    isCorrect ? (
      <Check className="h-5 w-5 text-emerald-800 dark:text-emerald-300" />
    ) : (
      <X className="h-5 w-5 text-red-700 dark:text-red-300" />
    )
  ) : null;

  const hasCommentsContent = Boolean(explanation || children);
  const canExpand = hasCommentsContent || showUpgradePrompt;
  // Show expand icon if there is expandable content (comments or upgrade prompt)
  const expandIcon = canExpand && (
    isExpanded ? (
      <ChevronUp className="h-4 w-4 text-slate-600 dark:text-slate-300 ml-2" />
    ) : (
      <ChevronDown className="h-4 w-4 text-slate-600 dark:text-slate-300 ml-2" />
    )
  );

  return (
    <div
      className={cn(
        'leading-snug relative cursor-pointer -my-px border-y-[1px]',
        stateClasses
      )}
      onClick={handleClick}
    >
      <div className="pl-6 pr-4 py-3 flex items-center cursor-pointer">
        <div role="button" className="pr-2 grow flex relative items-center cursor-pointer">
          <div className={cn(
            'leading-none text-lg shrink-0 flex font-bold uppercase justify-center items-center cursor-pointer',
            letterClasses
          )}>
            {optionLetter}
          </div>
          <div className="pl-4 grow cursor-pointer flex items-center gap-2">
            <p className="cursor-pointer text-sm">{optionText}</p>
            {isRevealed && isAIGenerated && (
              <Badge variant="secondary" className="text-xs px-1.5 py-0.5 bg-purple-100 dark:bg-purple-900/40 text-purple-700 dark:text-purple-300 border-purple-200 dark:border-purple-800">
                <Sparkles className="h-3 w-3 mr-1" />
                KI
              </Badge>
            )}
          </div>
        </div>
        <div className="mr-4 flex justify-center items-center gap-1.5 cursor-pointer">
          {isRevealed && showPercentage && modelIcons.length > 0 && (
            <div className="flex items-center gap-1">
              {modelIcons.map((model) => (
                <ModelIcon key={model} model={model} />
              ))}
            </div>
          )}
          <p className="text-slate-500 leading-none text-xs font-sans font-semibold cursor-pointer">
            {isRevealed && showPercentage ? (percentage !== null ? `${Math.round(percentage)}%` : '-') : ''}
          </p>
        </div>
        <div className="h-[38px] flex justify-center items-center cursor-pointer gap-1">
          {icon}
          {expandIcon}
        </div>
      </div>
      {isExpanded && (
        <div className="cursor-pointer">
          {hasCommentsContent && !showUpgradePrompt ? (
            <div
              className={cn(
                'border-t-[1px] text-sm',
                isRevealed && isCorrect
                  ? 'border-t-[#0b8363] bg-teal-50 dark:border-emerald-500 dark:bg-emerald-900/40'
                  : 'border-t-slate-200 dark:border-slate-700'
              )}
            >
              <div className="pr-6 pl-12 py-2">
                <div className="pl-6 space-y-4 prose prose-sm max-w-none">
                  {explanation && <ReactMarkdown>{explanation}</ReactMarkdown>}
                  {children}
                </div>
              </div>
            </div>
          ) : (
            <div className="border-t-[1px] border-t-slate-200 bg-slate-50 dark:border-slate-700 dark:bg-slate-800 text-sm">
              <div className="pr-6 pl-12 py-2">
                <div className="pl-6">
                  {showUpgradePrompt ? (
                    <div className="space-y-3">
                      <p className="text-slate-600 dark:text-slate-200">
                        Tägliches Limit für kostenlose KI-Kommentare erreicht. <a href="/subscription" className="text-blue-600 dark:text-blue-400">Jetzt upgraden</a>
                      </p>
                    </div>
                  ) : (
                    <p className="text-slate-600 dark:text-slate-200">Keine KI-Kommentare verfügbar</p>
                  )}
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}; 