// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynzxzhpivcmkpipanltd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inluenh6aHBpdmNta3BpcGFubHRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MTY4NTksImV4cCI6MjA1MzM5Mjg1OX0.KfoqDXjRZ8v5OuhRpPq-1wx3TdN9HABujMfbnfXcsec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
  },
});

// Ensure session is loaded on initialization
if (typeof window !== 'undefined') {
  supabase.auth.getSession().catch((error) => {
    console.error('Error loading session:', error);
  });
}